### PR TITLE
Refactored Importer

### PR DESCRIPTION
**Pull request by Stevoni**
The main change is the refactoring of the index page into separate classes and files.
Additionally, updated the MySql calls to the PDO object since the calls that were used will soon be obsoleted.

[Review on Reviewable](https://reviewable.io/reviews/skacekamen/wot-data-importer/1)

### CODE REVIEW

**Comment by SkaceKamen** [comment]
Wow, that looks nice, I'll try to review changes and merge it ASAP

**Comment by LesBear** [comment]
Hello
On the file wot_import.class.php line 167 have a syntax error.. 
`$versionIdNumber = $mysql->row($exists)['id'];`

And i also don´t understand how i should setup the WOT_PATH in the config.php 
`define('WOT_PATH', 'E:\\Games\\World_of_Tanks\\World_of_Tanks - 9.9 Clean\\');` 

I did update all files from here with the new data.

Can i get some help with that?
Thanks in advance
LesBear

**Comment by SkaceKamen** [comment]
It may now work anymore, since the data files are now inside pack files too. I have new importer, I can publish it if you need it

**Comment by LesBear** [comment]
Hi, yes if i can get all newest files should just be fine..
Thanks bud
LesBear

**Comment by SkaceKamen** [comment]
Here you go: https://github.com/SkaceKamen/wot-loader

**Comment by LesBear** [comment]
Thanks alot
LesBear

**Comment by LesBear** [comment]
Hello
I cant find this in the files you sent me.. autoload.php
`require __DIR__ . '/vendor/autoload.php';`
And also how do i setup the valules.php right? 
`<?php
return array(
	'paths' => array(
		'game' => 'E:/Games/World_of_Tanks/',
		'versions' => 'data/versions/',
		'texts' => 'data/texts/'
	),
	'mysql' => array(
		'hostname' => 'localhost',
		'username' => '****',
		'password' => '****',
		'database' => 'wot',
		'charset' => 'utf8'
	)
);` 
Do i just point it to my game folder?

I also installed the composer on this path:
`php56 /usr/local/bin/composer` I have a synology box...

Thanks in advance
LesBear

**Comment by SkaceKamen** [comment]
You need to have composer (https://getcomposer.org/) installed and run `composer install` in the repository directory.

In the values, you should change `game` to path to the game and mysql to your database credentials.

Also this is completely in off topic, we should move the discussion to new repo.

**Comment by LesBear** [comment]
Hello
Now i have the composer in my working folder 
composer 
And i also put the right path in the values.php to my game, but still don´t get it function
path 

Best Regards
LesBear

**Comment by SkaceKamen** [comment]
Please continue with discussion here https://github.com/SkaceKamen/wot-loader/issues/1

**Pull request merged**
